### PR TITLE
Light theme

### PR DESCRIPTION
**Pull request by gkeep**
I think it's time to roll light theme out of beta (it's been 6 months!), which is why I self-assigned myself to porting light theme to VSCode.

There are still a few rough edges (which is why it's still WIP), but enough is done to discuss it.

Preview:
image

Here's a TODO/FIXME list:
- [x] ~Colors look bleak compared to vim~ Looks like a font thickness problem.

- [x] Borders on some parts are wrong

- [x] Highlight on some parts are wrong

### CODE REVIEW

**Comment by gkeep** [comment]
Looks ready for review!

image

**Comment by cocopon** [comment]
Great work! and sorry for my too late reply... looking into it.

**Comment by cocopon** [comment]
**Tree indent guides**:
It looks too strong. Could you adjust them?
image

**Comment by cocopon** [comment]
**Terminal background**:
I think that it should be same as the default background because that is what the original Iceberg does.
image

**Comment by gkeep** [comment]
Sounds good, I'll look into it.

**Comment by cocopon** [comment]
**Indent characters and guides**:
It also looks too strong. How about applying `SpecialKey` to indent characters?
image

**Comment by gkeep** [comment]
> Tree indent

Looks like I forgot to change it in the first place. Same goes for Indent characters and guides.

**Comment by cocopon** [comment]
**Keyword highlightings in the quick input** (`list.highlightForeground`):
Maybe the light version of green should be used here:
image

**Comment by cocopon** [comment]
**Foreground color for changed items in explorer view**:
Maybe the light version of orange should be used here:
image

**Comment by gkeep** [comment]
Fixed a lot of things, please review!

**Comment by cocopon** [comment]
Could you re-check color definitions? All colors for dark mode (`#e27878**` for red, `#95c4ce**` for light blue, `#e2a478**` for orange, etc.) should be replaced with the light version. These colors are fine-tuned carefully to fit to the light background.

image

**Comment by cocopon** [comment]
**Whitespace characters**:
Could you apply `SpecialKey` to them? It looks too strong.
image

**Comment by cocopon** [comment]
**Peek view title**:
Title of the peek view looks hard to see.
image

**Comment by gkeep** [comment]
Peek window:
image

Whitespace characters:
image

**Comment by cocopon** [comment]
**Border in quick input**
It seems too strong.
vsc-border-too-strong

**Comment by cocopon** [comment]
**Keyword highlightings** 
Orange color should be applied there:
vsc-wrong-keyword-highlight-1

vsc-wrong-keyword-highlight-0

**Comment by gkeep** [comment]
Borders:
- In menus:
image
- In command palette / quick input:
image

Keyword highlights:
image

**Comment by cocopon** [comment]
**Borders are invisible**
Borders (between separated terminals and the bottom panel) looks invisible.

**Comment by cocopon** [comment]
Maybe still having many minor issues but enough to merge! Could you squash all commits into one?

**Comment by gkeep** [comment]
I'm pretty sure you can squash them when merging. 

Should be an option "Squash and merge".

E: In repository settings
image

**Comment by cocopon** [comment]
Maybe that option will push a squashed commit directly so merge commit will not be created. I prefer squashing manually and creating a merge commit.
image
https://github.blog/2016-04-01-squash-your-commits/

**Comment by gkeep** [comment]
Okay, I'll look into it once all major issues are fixed.

**Comment by cocopon** [comment]
> Maybe that option will push a squashed commit directly so merge commit will not be created. I prefer squashing manually and creating a merge commit.

Ah, maybe there is no difference between them...? (I have never used this option)

**Comment by gkeep** [comment]
It just creates one commit "Merge [branch] to [default branch]" like usual merges. In commit comment it lists all commits under development branch.

img

**Comment by gkeep** [comment]
How's this for borders?

image

**Comment by cocopon** [comment]
> It just creates one commit "Merge [branch] to [default branch]" like usual merges.

Thank you, I'll try to use that option.

> How's this for borders?

Looks good!

**Comment by cocopon** [comment]
Merged, thank you for your help!

image
and okay now I understand the behavior of `squash and merge`. I still prefer the previous style (squash manually and then merge it).

**Comment by gkeep** [comment]
Great news! Don't forget to bump the package version!

**Comment by cocopon** [comment]
I'll publish the package after fine-tuning and refactoring the whole code.

**Comment by cocopon** [comment]
Just published 2.0.0! Big thanks to @gkeep!

**Pull request merged**
